defmodule EdibAppTestCi do
  @input_data """
  # Hello from EDIB App Test CI!

  This output was generated by [`Cmark`](https://github.com/asaaki/cmark.ex).

  -----

  _Thank you for your attention!_
  """

  def run do
    hello
    :init.stop(0)
  end

  defp hello do
    @input_data
    |> Cmark.to_commonmark
    |> Cmark.to_html
    |> IO.puts
  end
end
